AWSTemplateFormatVersion: '2010-09-09'
Description: 'DIAL EKS Cluster with OIDC provider'

Parameters:
  ClusterName:
    Type: String
  
  KubernetesVersion:
    Type: String
    Default: '1.33'
  
  VPCId:
    Type: String
  
  PrivateSubnet1Id:
    Type: String
  
  PrivateSubnet2Id:
    Type: String
  
  EKSSecurityGroupId:
    Type: String
  
  PrivateRouteTableId:
    Type: String
    Description: Private route table ID for S3 Gateway endpoint
  
  AutoNodePools:
    Type: CommaDelimitedList
    Default: "system,general-purpose"
    Description: Built-in EKS Auto Mode NodePools to enable (system,general-purpose)

Resources:
  # VPC Endpoints Security Group
  VPCESecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for VPC Endpoints (EKS requirements)
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 10.0.0.0/8
      Tags:
        - Key: Name
          Value: !Sub '${ClusterName}-vpce-sg'

  # Required VPC Endpoints for EKS (air-gapped)
  EC2Endpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPCId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ec2'
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id
      SecurityGroupIds:
        - !Ref VPCESecurityGroup

  ECRApiEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPCId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ecr.api'
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id
      SecurityGroupIds:
        - !Ref VPCESecurityGroup

  ECRDkrEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPCId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ecr.dkr'
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id
      SecurityGroupIds:
        - !Ref VPCESecurityGroup

  S3Endpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPCId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      VpcEndpointType: Gateway
      RouteTableIds:
        - !Ref PrivateRouteTableId

  STSEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPCId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.sts'
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id
      SecurityGroupIds:
        - !Ref VPCESecurityGroup

  EKSVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPCId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.eks'
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id
      SecurityGroupIds:
        - !Ref VPCESecurityGroup

  ELBVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPCId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.elasticloadbalancing'
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id
      SecurityGroupIds:
        - !Ref VPCESecurityGroup

  CognitoIdpVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPCId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.cognito-idp'
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds:
        - !Ref PrivateSubnet2Id
      SecurityGroupIds:
        - !Ref VPCESecurityGroup

  # EKS Cluster IAM Role
  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ClusterName}-cluster-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: eks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
              - 'sts:TagSession'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEKSClusterPolicy'
        - 'arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly'
        - 'arn:aws:iam::aws:policy/AmazonEKSComputePolicy'
        - 'arn:aws:iam::aws:policy/AmazonEKSBlockStoragePolicy'
        - 'arn:aws:iam::aws:policy/AmazonEKSLoadBalancingPolicy'
        - 'arn:aws:iam::aws:policy/AmazonEKSNetworkingPolicy'
      Tags:
        - Key: Name
          Value: !Sub '${ClusterName}-cluster-role'

  # EKS Node IAM Role
  EKSNodeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ClusterName}-node-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEKSWorkerNodeMinimalPolicy'
        - 'arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPullOnly'
      Tags:
        - Key: Name
          Value: !Sub '${ClusterName}-node-role'

  # EKS Cluster
  EKSCluster:
    Type: AWS::EKS::Cluster
    DependsOn:
      - EC2Endpoint
      - ECRApiEndpoint
      - ECRDkrEndpoint
      - S3Endpoint
      - STSEndpoint
      - EKSVPCEndpoint
      - ELBVPCEndpoint
      - CognitoIdpVPCEndpoint
    Properties:
      Name: !Ref ClusterName
      Version: !Ref KubernetesVersion
      RoleArn: !GetAtt EKSClusterRole.Arn
      AccessConfig:
        AuthenticationMode: API
      KubernetesNetworkConfig:
        ServiceIpv4Cidr: 172.20.0.0/16
        IpFamily: ipv4
        ElasticLoadBalancing:
          Enabled: true
      # Enable EKS Auto Mode compute + block storage capabilities (no managed node groups).
      ComputeConfig:
        Enabled: true
        NodePools: !Ref AutoNodePools
        NodeRoleArn: !GetAtt EKSNodeRole.Arn
      StorageConfig:
        BlockStorage:
          Enabled: true
      ResourcesVpcConfig:
        SubnetIds:
          - !Ref PrivateSubnet1Id
          - !Ref PrivateSubnet2Id
        EndpointPrivateAccess: true
        EndpointPublicAccess: true
      Logging:
        ClusterLogging:
          EnabledTypes:
            - Type: api
            - Type: audit
            - Type: authenticator
            - Type: controllerManager
            - Type: scheduler
      Tags:
        - Key: Name
          Value: !Ref ClusterName

  # OIDC Provider
  OIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: !GetAtt EKSCluster.OpenIdConnectIssuerUrl
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        # EKS OIDC thumbprint - valid for all regions
        - '9e99a48a9960b14926bb7f3b02e22da2b0ab7280'
      Tags:
        - Key: Name
          Value: !Sub '${ClusterName}-oidc-provider'

  # Optional: match dial-poc baseline addons (managed by EKS)
  PodIdentityAgentAddon:
    Type: AWS::EKS::Addon
    DependsOn: EKSCluster
    Properties:
      ClusterName: !Ref ClusterName
      AddonName: eks-pod-identity-agent
      ResolveConflicts: OVERWRITE

  MetricsServerAddon:
    Type: AWS::EKS::Addon
    DependsOn: EKSCluster
    Properties:
      ClusterName: !Ref ClusterName
      AddonName: metrics-server
      ResolveConflicts: OVERWRITE
      ConfigurationValues: |
        nodeSelector:
          karpenter.sh/nodepool: system

Outputs:
  ClusterName:
    Description: EKS Cluster Name
    Value: !Ref ClusterName
    Export:
      Name: !Sub '${AWS::StackName}-ClusterName'

  ClusterArn:
    Description: EKS Cluster ARN
    Value: !GetAtt EKSCluster.Arn

  ClusterEndpoint:
    Description: EKS Cluster Endpoint
    Value: !GetAtt EKSCluster.Endpoint

  OIDCProviderArn:
    Description: OIDC Provider ARN
    Value: !GetAtt OIDCProvider.Arn
    Export:
      Name: !Sub '${AWS::StackName}-OIDCProviderArn'

  OIDCProviderUrl:
    Description: OIDC Provider URL
    Value: !GetAtt EKSCluster.OpenIdConnectIssuerUrl
    Export:
      Name: !Sub '${AWS::StackName}-OIDCProviderUrl'

  ClusterSecurityGroupId:
    Description: EKS Cluster Security Group ID (used by nodes)
    Value: !GetAtt EKSCluster.ClusterSecurityGroupId
    Export:
      Name: !Sub '${AWS::StackName}-ClusterSecurityGroupId'

  NodeRoleArn:
    Description: Node IAM Role ARN
    Value: !GetAtt EKSNodeRole.Arn
