AWSTemplateFormatVersion: '2010-09-09'
Description: 'DIAL IAM Roles for Service Accounts (IRSA)'

Parameters:
  OIDCProviderArn:
    Type: String
  OIDCProviderUrl:
    Type: String
  S3BucketName:
    Type: String
  RedisCacheArn:
    Type: String
  RedisUserArn:
    Type: String

Resources:
  CoreServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-core-service-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref OIDCProviderArn
            Action: 'sts:AssumeRoleWithWebIdentity'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
      Policies:
        - PolicyName: ElastiCacheAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: ['elasticache:Connect']
                Resource: [!Ref RedisCacheArn, !Ref RedisUserArn]

  BedrockServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-bedrock-service-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref OIDCProviderArn
            Action: 'sts:AssumeRoleWithWebIdentity'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonBedrockFullAccess'

  AssistantServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-assistant-service-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref OIDCProviderArn
            Action: 'sts:AssumeRoleWithWebIdentity'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonBedrockFullAccess'

Outputs:
  CoreRoleArn:
    Value: !GetAtt CoreServiceRole.Arn
  BedrockRoleArn:
    Value: !GetAtt BedrockServiceRole.Arn
  ALBControllerRoleArn:
    Value: !GetAtt AssistantServiceRole.Arn
