AWSTemplateFormatVersion: '2010-09-09'
Description: 'DIAL IAM Roles for Service Accounts (IRSA)'

Parameters:
  DeploymentName:
    Type: String
    Description: Base deployment name used as a prefix for stable IAM role names (must keep resulting RoleName <= 64 chars)
  OIDCProviderArn:
    Type: String
  OIDCProviderUrl:
    Type: String
  S3BucketName:
    Type: String
  RedisCacheArn:
    Type: String
  RedisUserArn:
    Type: String

Resources:
  CoreServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-core-service-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref OIDCProviderArn
            Action: 'sts:AssumeRoleWithWebIdentity'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
      Policies:
        - PolicyName: ElastiCacheAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: ['elasticache:Connect']
                Resource: [!Ref RedisCacheArn, !Ref RedisUserArn]
        - PolicyName: LicenseManagerReadAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'license-manager:ListDistributedGrants'
                  - 'license-manager:ListLicenseAssetRulesets'
                  - 'license-manager:ListLicenseConfigurations'
                  - 'license-manager:ListLicenseConfigurationsForOrganization'
                  - 'license-manager:ListReceivedLicenses'
                  - 'license-manager:GetServiceSettings'
                  - 'license-manager:ListAssetsForLicenseAssetGroup'
                  - 'license-manager:GetLicenseAssetRuleset'
                  - 'license-manager:ListUsageForLicenseConfiguration'
                  - 'license-manager:ListLicenseSpecificationsForResource'
                  - 'license-manager:GetLicenseManagerReportGenerator'
                  - 'license-manager:ListTagsForResource'
                  - 'license-manager:ListAssociationsForLicenseConfiguration'
                  - 'license-manager:GetLicenseConfiguration'
                  - 'license-manager:ListReceivedGrants'
                  - 'license-manager:GetLicenseConversionTask'
                  - 'license-manager:GetLicenseAssetGroup'
                  - 'license-manager:ListReceivedLicensesForOrganization'
                  - 'license-manager:ListResourceInventory'
                  - 'license-manager:ListLicenseConversionTasks'
                  - 'license-manager:ListLicenseAssetGroups'
                  - 'license-manager:ListTokens'
                  - 'license-manager:GetAccessToken'
                  - 'license-manager:ListLicenses'
                  - 'license-manager:ListLicenseManagerReportGenerators'
                  - 'license-manager:GetLicenseUsage'
                  - 'license-manager:GetLicense'
                  - 'license-manager:ListFailuresForLicenseConfigurationOperations'
                  - 'license-manager:ListLicenseVersions'
                  - 'license-manager:GetGrant'
                  - 'license-manager:ListReceivedGrantsForOrganization'
                Resource: '*'

  BedrockServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-bedrock-service-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref OIDCProviderArn
            Action: 'sts:AssumeRoleWithWebIdentity'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonBedrockFullAccess'

  AppControllerServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${DeploymentName}-app-controller-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref OIDCProviderArn
            Action: 'sts:AssumeRoleWithWebIdentity'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess'

  ALBControllerPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub '${AWS::StackName}-alb-controller-policy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'iam:CreateServiceLinkedRole'
            Resource: '*'
            Condition:
              "StringEquals":
                "iam:AWSServiceName": elasticloadbalancing.amazonaws.com
          - Effect: Allow
            Action:
              - 'ec2:DescribeAccountAttributes'
              - 'ec2:DescribeAddresses'
              - 'ec2:DescribeAvailabilityZones'
              - 'ec2:DescribeInternetGateways'
              - 'ec2:DescribeVpcs'
              - 'ec2:DescribeVpcPeeringConnections'
              - 'ec2:DescribeSubnets'
              - 'ec2:DescribeSecurityGroups'
              - 'ec2:DescribeInstances'
              - 'ec2:DescribeNetworkInterfaces'
              - 'ec2:DescribeTags'
              - 'ec2:GetCoipPoolUsage'
              - 'ec2:DescribeCoipPools'
              - 'ec2:GetSecurityGroupsForVpc'
              - 'ec2:DescribeIpamPools'
              - 'ec2:DescribeRouteTables'
              - 'elasticloadbalancing:DescribeLoadBalancers'
              - 'elasticloadbalancing:DescribeLoadBalancerAttributes'
              - 'elasticloadbalancing:DescribeListeners'
              - 'elasticloadbalancing:DescribeListenerCertificates'
              - 'elasticloadbalancing:DescribeSSLPolicies'
              - 'elasticloadbalancing:DescribeRules'
              - 'elasticloadbalancing:DescribeTargetGroups'
              - 'elasticloadbalancing:DescribeTargetGroupAttributes'
              - 'elasticloadbalancing:DescribeTargetHealth'
              - 'elasticloadbalancing:DescribeTags'
              - 'elasticloadbalancing:DescribeTrustStores'
              - 'elasticloadbalancing:DescribeListenerAttributes'
              - 'elasticloadbalancing:DescribeCapacityReservation'
            Resource: '*'
          - Effect: Allow
            Action:
              - 'cognito-idp:DescribeUserPoolClient'
              - 'acm:ListCertificates'
              - 'acm:DescribeCertificate'
              - 'iam:ListServerCertificates'
              - 'iam:GetServerCertificate'
              - 'waf-regional:GetWebACL'
              - 'waf-regional:GetWebACLForResource'
              - 'waf-regional:AssociateWebACL'
              - 'waf-regional:DisassociateWebACL'
              - 'wafv2:GetWebACL'
              - 'wafv2:GetWebACLForResource'
              - 'wafv2:AssociateWebACL'
              - 'wafv2:DisassociateWebACL'
              - 'shield:GetSubscriptionState'
              - 'shield:DescribeProtection'
              - 'shield:CreateProtection'
              - 'shield:DeleteProtection'
            Resource: '*'
          - Effect: Allow
            Action:
              - 'ec2:AuthorizeSecurityGroupIngress'
              - 'ec2:RevokeSecurityGroupIngress'
            Resource: '*'
          - Effect: Allow
            Action:
              - 'ec2:CreateSecurityGroup'
            Resource: '*'
          - Effect: Allow
            Action:
              - 'ec2:CreateTags'
            Resource: 'arn:aws:ec2:*:*:security-group/*'
            Condition:
              "StringEquals":
                "ec2:CreateAction": CreateSecurityGroup
              "Null":
                "aws:RequestTag/elbv2.k8s.aws/cluster": 'false'
          - Effect: Allow
            Action:
              - 'ec2:CreateTags'
              - 'ec2:DeleteTags'
            Resource: 'arn:aws:ec2:*:*:security-group/*'
            Condition:
              "Null":
                "aws:RequestTag/elbv2.k8s.aws/cluster": 'true'
                "aws:ResourceTag/elbv2.k8s.aws/cluster": 'false'
          - Effect: Allow
            Action:
              - 'ec2:AuthorizeSecurityGroupIngress'
              - 'ec2:RevokeSecurityGroupIngress'
              - 'ec2:DeleteSecurityGroup'
            Resource: '*'
            Condition:
              "Null":
                "aws:ResourceTag/elbv2.k8s.aws/cluster": 'false'
          - Effect: Allow
            Action:
              - 'elasticloadbalancing:CreateLoadBalancer'
              - 'elasticloadbalancing:CreateTargetGroup'
            Resource: '*'
            Condition:
              "Null":
                "aws:RequestTag/elbv2.k8s.aws/cluster": 'false'
          - Effect: Allow
            Action:
              - 'elasticloadbalancing:CreateListener'
              - 'elasticloadbalancing:DeleteListener'
              - 'elasticloadbalancing:CreateRule'
              - 'elasticloadbalancing:DeleteRule'
            Resource: '*'
          - Effect: Allow
            Action:
              - 'elasticloadbalancing:AddTags'
              - 'elasticloadbalancing:RemoveTags'
            Resource:
              - 'arn:aws:elasticloadbalancing:*:*:targetgroup/*/*'
              - 'arn:aws:elasticloadbalancing:*:*:loadbalancer/net/*/*'
              - 'arn:aws:elasticloadbalancing:*:*:loadbalancer/app/*/*'
            Condition:
              "Null":
                "aws:RequestTag/elbv2.k8s.aws/cluster": 'true'
                "aws:ResourceTag/elbv2.k8s.aws/cluster": 'false'
          - Effect: Allow
            Action:
              - 'elasticloadbalancing:AddTags'
              - 'elasticloadbalancing:RemoveTags'
            Resource:
              - 'arn:aws:elasticloadbalancing:*:*:listener/net/*/*/*'
              - 'arn:aws:elasticloadbalancing:*:*:listener/app/*/*/*'
              - 'arn:aws:elasticloadbalancing:*:*:listener-rule/net/*/*/*'
              - 'arn:aws:elasticloadbalancing:*:*:listener-rule/app/*/*/*'
          - Effect: Allow
            Action:
              - 'elasticloadbalancing:ModifyLoadBalancerAttributes'
              - 'elasticloadbalancing:SetIpAddressType'
              - 'elasticloadbalancing:SetSecurityGroups'
              - 'elasticloadbalancing:SetSubnets'
              - 'elasticloadbalancing:DeleteLoadBalancer'
              - 'elasticloadbalancing:ModifyTargetGroup'
              - 'elasticloadbalancing:ModifyTargetGroupAttributes'
              - 'elasticloadbalancing:DeleteTargetGroup'
              - 'elasticloadbalancing:ModifyListenerAttributes'
              - 'elasticloadbalancing:ModifyCapacityReservation'
              - 'elasticloadbalancing:ModifyIpPools'
            Resource: '*'
            Condition:
              "Null":
                "aws:ResourceTag/elbv2.k8s.aws/cluster": 'false'
          - Effect: Allow
            Action:
              - 'elasticloadbalancing:AddTags'
            Resource:
              - 'arn:aws:elasticloadbalancing:*:*:targetgroup/*/*'
              - 'arn:aws:elasticloadbalancing:*:*:loadbalancer/net/*/*'
              - 'arn:aws:elasticloadbalancing:*:*:loadbalancer/app/*/*'
            Condition:
              "StringEquals":
                "elasticloadbalancing:CreateAction":
                  - CreateTargetGroup
                  - CreateLoadBalancer
              "Null":
                "aws:RequestTag/elbv2.k8s.aws/cluster": 'false'
          - Effect: Allow
            Action:
              - 'elasticloadbalancing:RegisterTargets'
              - 'elasticloadbalancing:DeregisterTargets'
            Resource: 'arn:aws:elasticloadbalancing:*:*:targetgroup/*/*'
          - Effect: Allow
            Action:
              - 'elasticloadbalancing:SetWebAcl'
              - 'elasticloadbalancing:ModifyListener'
              - 'elasticloadbalancing:AddListenerCertificates'
              - 'elasticloadbalancing:RemoveListenerCertificates'
              - 'elasticloadbalancing:ModifyRule'
              - 'elasticloadbalancing:SetRulePriorities'
            Resource: '*'

  ALBControllerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-alb-controller-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref OIDCProviderArn
            Action: 'sts:AssumeRoleWithWebIdentity'
      ManagedPolicyArns:
        - !Ref ALBControllerPolicy

Outputs:
  CoreRoleArn:
    Value: !GetAtt CoreServiceRole.Arn
  BedrockRoleArn:
    Value: !GetAtt BedrockServiceRole.Arn
  AppControllerRoleArn:
    Value: !GetAtt AppControllerServiceRole.Arn
  ALBControllerRoleArn:
    Value: !GetAtt ALBControllerRole.Arn
